mex -setup:'C:\Program Files\MATLAB\R2014a\bin\win64\mexopts\msvcpp110.xml' C++

mex -D'USE_MKL'...
    -D'BOOST_ALL_DYN_LINK'...
    -D'WIN32'...
    -D'NDEBUG'...
    -I"D:\Git\caffe\include" ...
    -I"D:\Git\caffe\src" ...
    -I"D:\Git\caffe\3rdparty\include"...
    -I"D:\Git\caffe\3rdparty\include\hdf5"...
    -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include"...
    -I"C:\Program Files (x86)\Intel\Composer XE 2013\mkl\include"...
    -L"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\lib"...
    -L"C:\Program Files (x86)\Intel\Composer XE 2013\mkl\lib\intel64"...
    -L"D:\Git\caffe\3rdparty\lib"...
    -L"D:\Git\caffe\bin"...
    -l'caffe_windows.lib'...
    -l'opencv_highgui248.lib'...
    -l'opencv_core248.lib'...
    -l'opencv_imgproc248.lib'...
    -l'shlwapi.lib'...
    -l'leveldb.lib'...
    -l'libgsl-0.lib'...
    -l'libgslcblas-0.lib'...
    -l'cublas.lib'...
    -l'cublas_device.lib'...
    -l'curand.lib'...
    -l'cudart.lib'...
    -l'cuda.lib'...
    -l'libprotobuf.lib'...
    -l'libglog.lib'...
    matcaffe.cpp

copyfile('matcaffe.mexw64', '../../bin/caffe.mexw64');